wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720106465
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.10.0
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 32
